### ISSUE TITLE
This API is so shit...

### ISSUE THREAD

**Issue by SaucyGames05** [gedeondoescode/hubris-web#1]
what the fuck is this bullshit? like bro, if you finna make an api you best do it right. not what this mfer did. open source? open source deez nuts into yo mouth bitch.

Love, Your bestie,
femboycocksucker69 aka SaucyGames05

**Comment by gedeondoescode** [comment]
> what the fuck is this bullshit? like bro, if you finna make an api you best do it right. not what this mfer did. open source? open source deez nuts into yo mouth bitch.
> 
> Love, Your bestie,
> femboycocksucker69 aka SaucyGames05

okay fuck you then
